### ISSUE TITLE
jax not installed properly

### ISSUE THREAD

**Issue by gotero** [google-deepmind/alphafold3#141]
Built the docker container and created a singularity container from that. 

On our GPU node (NVIDIA RTX A5000, NVIDIA-SMI 550.120, Driver Version: 550.120, CUDA Version: 12.4) I'm getting xla and jax errors -

```
I1127 22:33:41.859019 139158955212800 folding_input.py:1044] Detected /root/af_input/test_input.json is an AlphaFold 3 JSON since the top-level is not a list.
2024-11-27 22:33:42.112759: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Traceback (most recent call last):
File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 885, in backends
backend = _init_backend(platform)
^^^^^^^^^^^^^^^^^^^^^^^
File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 971, in _init_backend
backend = registration.factory()
^^^^^^^^^^^^^^^^^^^^^^
File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 671, in factory
return xla_client.make_c_api_client(plugin_name, updated_options, None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/alphafold3_venv/lib/python3.11/site-packages/jaxlib/xla_client.py", line 200, in make_c_api_client
return _xla.get_c_api_client(plugin_name, options, distributed_client)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: No visible GPU devices.

JAX:
Traceback (most recent call last):
File "/home/gleno/alphafold3/run_alphafold.py", line 716, in
app.run(main)
File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
_run_main(main, args)
File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
sys.exit(main(argv))
^^^^^^^^^^
File "/home/gleno/alphafold3/run_alphafold.py", line 630, in main
gpu_devices = jax.local_devices(backend='gpu')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 1141, in local_devices
process_index = get_backend(backend).process_index()
^^^^^^^^^^^^^^^^^^^^
File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 1017, in get_backend
return _get_backend_uncached(platform)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 996, in _get_backend_uncached
bs = backends()
^^^^^^^^^^
File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 901, in backends
raise RuntimeError(err_msg)
RuntimeError: Unable to initialize backend 'cuda': FAILED_PRECONDITION: No visible GPU devices. (you may need to uninstall the failing plugin package, or set JAX_PLATFORMS=cpu to skip this backend.)

setting JAX_PLATFORMS=CPU gives this error:

INFO: underlay of /usr/bin/nvidia-smi required more than 50 (496) bind mounts
I1127 22:40:42.236124 131293118668800 folding_input.py:1044] Detected /root/af_input/test_input.json is an AlphaFold 3 JSON since the top-level is not a list.
Traceback (most recent call last):
File "/home/gleno/alphafold3/run_alphafold.py", line 716, in
app.run(main)
File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
_run_main(main, args)
File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
sys.exit(main(argv))
^^^^^^^^^^
File "/home/gleno/alphafold3/run_alphafold.py", line 630, in main
gpu_devices = jax.local_devices(backend='gpu')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 1141, in local_devices
process_index = get_backend(backend).process_index()
^^^^^^^^^^^^^^^^^^^^
File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 1017, in get_backend
return _get_backend_uncached(platform)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 998, in _get_backend_uncached
platform = canonicalize_platform(platform)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/alphafold3_venv/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 801, in canonicalize_platform
raise RuntimeError(f"Unknown backend: '{platform}' requested, but no "
RuntimeError: Unknown backend: 'gpu' requested, but no platforms that are instances of gpu are present. Platforms present are: cpu
```

Suggestions?

**Comment by jsspencer** [comment]
The problem is that the GPU is not available to the docker container. What command are you using to run AlphaFold 3? What version of docker are you using?

Can you ensure that the GPU is available in the docker container? A simple example, assuming the built docker image is called `alphafold`:

```
$ docker run -it --gpus all alphafold3:latest python -c "import jax; print(jax.local_devices())"
[CudaDevice(id=0)]
$ docker run -it alphafold3:latest python -c "import jax; print(jax.local_devices())"
[CpuDevice(id=0)]
```

For `run_alphafold.py` to work correctly, `jax.local_devices()[0]` needs to be a `CudaDevice`.

**Comment by gotero** [comment]
Docker version 27.2.1, build 9e34c9b. 

I confirmed that CUDA Version: 12.5 is available to containers, driver version is 555.42.06.

I ran this command with the alphafold3 container to check for CudaDevices  "docker run --rm --gpus all alphafold3 python -c "import jax; print(jax.local_devices())"" and got this error:

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: requirement error: unsatisfied condition: cuda>=12.6, please update your driver to a newer version, or use an earlier cuda container: unknown.

So AF3 requires cuda>=12.6? 

Running the above command without "--gpus all" returns [CpuDevice(id=0)].

**Comment by jsspencer** [comment]
The Dockerfile supplied requires the host has CUDA 12.6 or higher, yes -- this is due to the CUDA version used inside the docker container. I think AF3 itself can run on older versions, but we have not extensively tested this, especially for numerical performance.

**Comment by gotero** [comment]
Hmmm... I got it working on an RTX A5000 with CUDA 12.4. run_alphafold_test.py completed in about 5 minutes.

**Comment by jsspencer** [comment]
Great! Just to re-iterate, please validate accuracy carefully as we have not extensively tested with older versions of CUDA.

**Comment by gotero** [comment]
Thank you!!
