### ISSUE TITLE
Singularity and CUDNN

### ISSUE THREAD

**Issue by danielsj1-chop** [google-deepmind/alphafold3#79]
When following the singularity setup instructions mentioned in #23 we run into this once we actually run the container/alphafold:

E1119 10:37:39.248565  283298 cuda_dnn.cc:502] There was an error before creating cudnn handle (500): cudaErrorSymbolNotFound : named symbol not found
E1119 10:37:39.265522  283298 cuda_dnn.cc:502] There was an error before creating cudnn handle (500): cudaErrorSymbolNotFound : named symbol not found
...
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

Are we missing a step somewhere? CUDNN seems built into the container and venv.

Thanks

**Comment by almeida85** [comment]
I had the same error.

**Comment by aozalevsky** [comment]
@danielsj1-chop @almeida85 can you provide `nvidia-smi` output from inside the container or the host machine? There are interdependencies  between cudnn, cuda, and nvidia driver versions https://docs.nvidia.com/deeplearning/cudnn/latest/reference/support-matrix.html#id17 https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id5 and i found the container works with the driver (on the host) at least `535.183.01` (though with a warning):
```
2024-11-19 20:50:18.724815: W external/xla/xla/service/gpu/nvptx_compiler.cc:930] The NVIDIA driver's CUDA version is 12.2 which is older than the PTX compiler version 12.6.77. Because the driver is older than the PTX compiler version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.
```
but fails with the same 
```
cudnn handle (500): cudaErrorSymbolNotFound : named symbol not found
```
error on `525.147.05`.

**Comment by ivandon15** [comment]
Please check if running the script below reproduces the same error:

```python
import jax.numpy as jnp
jnp.ones((3, 3))
```

If the error occurs, it is likely due to a version mismatch between JAX and your GPU driver. I resolved this issue by downgrading both `jax` and `jaxlib` to **0.4.33** instead of **0.4.34**.

**Comment by whecrane** [comment]
I followed your advice, and get this error:
```
alphafold3 3.0.0 requires jax==0.4.34, but you have jax 0.4.33 which is incompatible.
alphafold3 3.0.0 requires jax[cuda12]==0.4.34, but you have jax 0.4.33 which is incompatible.
jax-triton 0.2.0 requires jax>=0.4.34, but you have jax 0.4.33 which is incompatible.
```
It seems can't downgrade...

**Comment by ivandon15** [comment]
> I followed your advice, and get this error:
> 
> ```
> alphafold3 3.0.0 requires jax==0.4.34, but you have jax 0.4.33 which is incompatible.
> alphafold3 3.0.0 requires jax[cuda12]==0.4.34, but you have jax 0.4.33 which is incompatible.
> jax-triton 0.2.0 requires jax>=0.4.34, but you have jax 0.4.33 which is incompatible.
> ```
> 
> It seems can't downgrade...

This is expected because the `pyproject.toml` file in AF3 specifies `jax==0.4.34`, and the same applies to `jax-triton 0.2.0`. However, based on my testing, I found that `jax==0.4.33` is actually compatible with everything under AF3. So, as long as you successfully install `jax==0.4.33`, it should work.

The image below is a screenshot of the environment where AF3 ran successfully.
<img width="472" alt="envs" src="https://github.com/user-attachments/assets/2d49bd2b-91b7-42f8-9784-dd067be86fd6">

**Comment by danielsj1-chop** [comment]
Updating my cuda driver version on the host machine does indeed fix it.
Updated to 550.127.05 from 525.85.12

Thanks,
John

**Comment by Augustin-Zidek** [comment]
Brilliant, thanks everyone for helping to resolve this!

**Comment by wwl5600** [comment]
I had the same error. And my Driver Version: 525.105.17   CUDA Version: 12.0 , cuDNN 9.5.1,  JAX 0.4.34.  Do I need to reinstall my cuda driver?

![微信图片_20241126004228](https://github.com/user-attachments/assets/55e1826b-3bec-4efb-a8b8-1780c370a932)
![微信图片_20241126012339](https://github.com/user-attachments/assets/eb20387b-6afe-4fcb-beb3-9534c6188527)
![微信图片_202411260123391](https://github.com/user-attachments/assets/850b76b4-291f-4a3a-8bee-fc12ce2fb006)

**Comment by Augustin-Zidek** [comment]
Yes, I think so. I recommend updating the driver to the latest verion and CUDA to 12.6.
